---
name: docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - setuptools_scm
  - toml
  - black
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - sphinx-panels
  - ipython
  - ipython_genutils
  - nbsphinx
  - pydata-sphinx-theme<=0.12.0
  - myst-parser
